### ISSUE TITLE
can't you bust the dependency to oasis? [fix not released]

### ISSUE THREAD

**Issue by UnixJunkie** [mkur/nlopt-ocaml#8]

**Comment by UnixJunkie** [comment]
I am not even sure if it still maintained.

**Comment by mkur** [comment]
Already done - the master branch uses dune

**Comment by UnixJunkie** [comment]
But it was not released in opam, am I right?

**Comment by UnixJunkie** [comment]
Can't you issue a new tag.
The latest one if from 2014; cf. https://github.com/mkur/nlopt-ocaml/tags

**Comment by UnixJunkie** [comment]
released but the opam file needs to be updated
